--liquibase formatted sql

--changeset ratmir:1
CREATE TABLE IF NOT EXISTS hogwards_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(100) NOT NULL,
    enabled     BOOLEAN DEFAULT TRUE,
    roles       VARCHAR(256) NOT NULL
);