--liquibase formatted sql

--changeset ratmir:1
CREATE TABLE wizard (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

--changeset ratmir:2
CREATE TABLE artifact (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    image_url   VARCHAR(255),
    wizard_id   BIGINT REFERENCES wizard(id)
);